// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMtH3dnVbWEwloci0YSxwFe-_c7ecm6cM',
    appId: '1:214727794994:web:6650d7e1ecbe8aeea8772b',
    messagingSenderId: '214727794994',
    projectId: 'flutter-robinshorts',
    authDomain: 'flutter-robinshorts.firebaseapp.com',
    storageBucket: 'flutter-robinshorts.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB947EOKfz44GCNCEpIqZnLj7rD7MHtWIU',
    appId: '1:214727794994:android:795a5beb427a76b6a8772b',
    messagingSenderId: '214727794994',
    projectId: 'flutter-robinshorts',
    storageBucket: 'flutter-robinshorts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2lH1TOA0nvY29W34OL5Ql4DTq_57vB94',
    appId: '1:214727794994:ios:ad59e2fcd1c9b684a8772b',
    messagingSenderId: '214727794994',
    projectId: 'flutter-robinshorts',
    storageBucket: 'flutter-robinshorts.appspot.com',
    iosClientId: '214727794994-7t470und3c6bda8q0je2qu0fpsns9b5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRobinshorts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2lH1TOA0nvY29W34OL5Ql4DTq_57vB94',
    appId: '1:214727794994:ios:ad59e2fcd1c9b684a8772b',
    messagingSenderId: '214727794994',
    projectId: 'flutter-robinshorts',
    storageBucket: 'flutter-robinshorts.appspot.com',
    iosClientId: '214727794994-7t470und3c6bda8q0je2qu0fpsns9b5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRobinshorts',
  );
}
